### ISSUE TITLE
"make install" fails on macos

### ISSUE THREAD

**Issue by 0x15e** [MichaelDarr/docker-config#1]
Building ahab works fine but running `make install` results in the following error:

```
install -Dm755 ahab /usr/local/bin/ahab
install: illegal option -- D
usage: install [-bCcpSsv] [-B suffix] [-f flags] [-g group] [-m mode]
               [-o owner] file1 file2
       install [-bCcpSsv] [-B suffix] [-f flags] [-g group] [-m mode]
               [-o owner] file1 ... fileN directory
       install -d [-v] [-g group] [-m mode] [-o owner] directory ...
make: *** [install] Error 64
```

Installing coreutils and changing the install command used to "ginstall" seems to get things working, albeit with a sudo.

**Comment by MichaelDarr** [comment]
Since I don't own a Mac and MacOS can't be run trivially in a container, I only plan to support Linux installs for the time being. If you'd like to add Homebrew support, pull requests are always welcome!

**Comment by 0x15e** [comment]
Yeah I figured it was something like that. 

Something I read when I was looking up that error message was that the lower-case "-d" option could probably be used in place of "-D". Does "-d" work as well as "-D" for you on Linux? If so, the fix for this would be as simple as changing that switch.

**Comment by MichaelDarr** [comment]
After reading through the manpages of the macOS/GNU versions of install, it looks like the "d" option for macOS works the same as the "D" option for GNU. I've added logic to the Makefile to detect the OS and set the option accordingly  (f383b0588570df06cc1b29d45abafa536d2dcae7) - can you give it a try and confirm that it works on macOS? Everything looks good on the Linux side of things.

**Comment by 0x15e** [comment]
As much as they _should_ be equivalent (the docs definitely read that way), [it appears they aren't](https://superuser.com/questions/548017/how-to-properly-use-install-command-line-command-in-mac-os-x#answer-548975) (I ran into the problem that poster had when I tried using the new Makefile).

Let me take a look at this for a bit and see if I can get a PR together for you.

**Comment by MichaelDarr** [comment]
I just committed another approach to the macOS install (bd6b5a93bf56fd2e9a331abd057361f354421436) - could you try again and see if it works? I tried to test it myself in an emulator but it's being really finicky.

**Comment by 0x15e** [comment]
Unfortunately still no good. I'm getting this:

```
install -d -m 0755 ahab /usr/local/bin/ahab
install: ahab exists but is not a directory
make: *** [install] Error 71
```

The problem (I think) is that on a mac, that `-d` means "all these parameters are directories" and it has to be broken into two commands: one for directories and one for files. Kind of defeats the purpose of the `install` command IMO but I won't pretend most of the way macs work makes any sense.

**Comment by MichaelDarr** [comment]
Looks like in both commands, `-d` is used to signify that all arguments are directory names - whoops! Just pushed a commit (2560b9527e97afa30640add040f1b5c1e4f17cc9) getting rid of OS-specific install options (`-D`) in favor of universally supported ones. Hoping this works on macOS and we can close this issue out for good.

**Comment by 0x15e** [comment]
Yep that did it. Thanks!

**Comment by MichaelDarr** [comment]
Great, thanks for submitting the issue!
